Poetry as a package builder
neptune-ai/neptune-client pull request #1069
Opened 2022-10-28 15:34 UTC by Raalsky

2022-10-31 14:36 UTC, PatrykGala requested changes

2022-10-31 14:36 UTC, PatrykGala commented on .github/actions/tests-e2e/action.yml
> +          pip install pip install ".[dev,e2e]"
too many `pip install`

2022-10-31 14:36 UTC, PatrykGala commented on .github/actions/tests/action.yml
> +          pip install pip install ".[dev]"
remove one `pip install`

2022-10-31 14:41 UTC, Raalsky commented on .github/actions/tests-e2e/action.yml
> +          pip install pip install ".[dev,e2e]"
Fixed :wink:

2022-10-31 14:49 UTC, PatrykGala submitted a review, later dismissed

2022-11-02 09:56 UTC, shnela approved these changes

2022-11-03 09:38 UTC, shnela approved these changes

2022-11-03 09:45 UTC, merged