Added support of active projects exception
neptune-ai/neptune-client pull request #1348
Opened 2023-05-22 09:40 UTC by Raalsky

## Before submitting checklist

- [x] Did you **update the CHANGELOG**? (not for test updates, internal changes/refactors or CI/CD setup)
- [ ] Did you **ask the docs owner** to review all the user-facing changes?

2023-05-22 09:46 UTC, aniezurawski requested changes

2023-05-22 09:49 UTC, Raalsky commented on src/neptune/management/exceptions.py
> +    description = "Limit of active projects reached. You can have up to {currentQuota} active projects simultaneously."
Not in management API :wink:

2023-05-22 09:49 UTC, Raalsky commented on src/neptune/internal/backends/swagger_client_wrapper.py
> +                currentQuota=response_body.get("currentQuota", "<unknown key>")
Done

2023-05-22 09:54 UTC, Raalsky commented on src/neptune/management/exceptions.py
> +    description = "Limit of active projects reached. You can have up to {currentQuota} active projects simultaneously."
I remember that the main intention was to prepare some "easily processable" exceptions as they'll be mostly called in CI/CD workflows not by the users themselves. I'm not sure how many of these assumptions are up-to-date.

2023-05-22 09:58 UTC, aniezurawski commented on src/neptune/management/exceptions.py
> +    description = "Limit of active projects reached. You can have up to {currentQuota} active projects simultaneously."
Good error message and some `code` to be checked programmatically are not mutually exclusive. ;)

2023-05-24 19:20 UTC, normandy7 commented on src/neptune/management/exceptions.py
> +    description = "Limit of active projects reached. You can have up to {currentQuota} active projects simultaneously."
If we want to be more helpful, we can add more context and "what to do next", sure.

Is this exception thrown when you try `create_project()` but your quota is full?

2023-05-31 20:08 UTC, Raalsky commented on src/neptune/management/exceptions.py
> +    description = "Limit of active projects reached. You can have up to {currentQuota} active projects simultaneously."
> Is this exception thrown when you try create_project() but your quota is full?

Yes

2023-05-31 21:59 UTC, normandy7 reviewed
Proposed slightly more elaborate message.

2023-05-31 21:59 UTC, normandy7 commented on src/neptune/management/exceptions.py
> +    description = "Limit of active projects reached. You can have up to {currentQuota} active projects simultaneously."
```suggestion
    description = (
        "Limit of active projects reached. You can have up to {currentQuota} active projects simultaneously. "
        "To create a new project, you need to either archive an active project or increase the quota of active "
        "projects in the workspace."
    )
```

2023-06-01 07:46 UTC, normandy7 approved these changes

2023-06-02 13:37 UTC, aniezurawski approved these changes

2023-06-02 13:38 UTC, merged