chore: update changelog
neptune-ai/neptune-client pull request #1408
Opened 2023-07-26 07:59 UTC by PatrykGala

## Before submitting checklist

- [ ] Did you **update the CHANGELOG**? (not for test updates, internal changes/refactors or CI/CD setup)
- [ ] Did you **ask the docs owner** to review all the user-facing changes?

2023-07-26 08:04 UTC, AleksanderWWW requested changes

2023-07-26 08:04 UTC, AleksanderWWW commented on CHANGELOG.md
>  ##  neptune 1.4.0rc0
Change this to `1.4.0`

2023-07-26 08:04 UTC, AleksanderWWW commented on CHANGELOG.md
> +##  neptune 1.4.0rc1
change this to `1.4.1`

2023-07-27 13:09 UTC, SiddhantSadangi approved these changes

2023-07-27 13:20 UTC, AleksanderWWW approved these changes

2023-07-27 13:20 UTC, merged