Raise unsupported error for artifact dir
neptune-ai/neptune-client pull request #484
Opened 2021-03-26 12:44 UTC by shnela

2021-03-30 17:44 UTC, aniezurawski requested changes

2021-03-30 17:44 UTC, aniezurawski commented on neptune/exceptions.py
> +Neptune Client Library was not able to single file from sources.
The verb is missing.

2021-03-30 21:47 UTC, shnela commented on alpha_integration_dev/old_client.py
> +        # neptune.remove_tag('tag4_remove_non_existing')
It used to hang and losing connection with server in both situations, but now it works.

2021-03-31 05:55 UTC, aniezurawski approved these changes

2021-03-31 07:52 UTC, merged