Add UncaughtExceptionHandler
neptune-ai/neptune-client pull request #521
Opened 2021-04-26 10:33 UTC by HubertJaworski

2021-04-26 13:03 UTC, aniezurawski requested changes

2021-04-26 13:03 UTC, aniezurawski commented on neptune/new/internal/utils/uncaught_exception_handler.py
> +instance = UncaughtExceptionHandler()
Is this object thread-safe?

2021-04-26 13:03 UTC, aniezurawski commented on neptune/new/internal/utils/traceback_job.py
> +                run["sys/failed"] = Boolean(True)
Use constant.

2021-04-26 13:03 UTC, aniezurawski commented on neptune/new/internal/utils/traceback_job.py
> +        self.stop()
It should be empty. stop is called explicitly before join.

2021-04-26 14:08 UTC, HubertJaworski commented on neptune/new/internal/utils/uncaught_exception_handler.py
> +            sys.__excepthook__(exc_type, exc_val, exc_tb)
Copied from existing code. There was a call to `sys.__excepthook__`

2021-04-27 07:16 UTC, aniezurawski requested changes

2021-04-27 07:16 UTC, aniezurawski commented on neptune/new/internal/init_impl.py
> +        _run[attr_consts.SYSTEM_FAILED_ATTRIBUTE_PATH] = Boolean(False)
Just False should work as well.

2021-04-27 07:16 UTC, aniezurawski commented on neptune/new/internal/utils/traceback_job.py
> +                run["sys/failed"] = Boolean(True)
Just True. It should not be necessary to pack it.

2021-04-27 07:16 UTC, aniezurawski commented on neptune/new/attributes/constants.py
> +MONITORIC_TRACEBACK = f'{MONITORING_ATTRIBUTE_SPACE}traceback'
MONITOR**ING**_TRACEBACK_ATTRIBUTE_PATH

2021-04-27 07:16 UTC, aniezurawski commented on neptune/new/internal/utils/traceback_job.py
> +                run[path].log(stacktrace_lines)
What about this comment?

2021-04-27 07:16 UTC, aniezurawski commented on neptune/new/internal/utils/uncaught_exception_handler.py
> +        self.__lock__ = threading.Lock()
This naming convention is reserved for built-in things.

2021-04-27 09:59 UTC, HubertJaworski commented on neptune/new/internal/utils/traceback_job.py
> +                run[path].log(stacktrace_lines)
I chose not to do this at this point. We don't know what is valuable for user and stuff like hostname should be logged anyway in other attributes. The name of series is literally `traceback`, and for me, adding random stuff there will make this series harder to read

2021-04-27 10:21 UTC, aniezurawski commented on neptune/new/internal/utils/traceback_job.py
> +                run[path].log(stacktrace_lines)
I'm not sure if this is something to discuss. It make sense to have such information.
@Herudaio ?

2021-04-27 12:45 UTC, aniezurawski approved these changes

2021-04-27 12:52 UTC, merged