Draft: AssignArtifact operation
neptune-ai/neptune-client pull request #654
Opened 2021-08-13 10:23 UTC by Raalsky

2021-08-18 12:27 UTC, Raalsky commented on neptune/new/handler.py
> +    def track_files(self, path: str, wait: bool = True) -> None:
Add `namespace`

2021-08-19 07:02 UTC, pkasprzyk reviewed
looks great!

2021-08-19 07:02 UTC, pkasprzyk commented on neptune/new/internal/backends/hosted_artifact_operations.py
> +        entry_path, entry_namespace = entry
```suggestion
    for entry_path, entry_namespace in entries:
```

2021-08-19 14:02 UTC, pkasprzyk requested changes

2021-08-19 14:02 UTC, pkasprzyk commented on neptune/new/internal/backends/api_model.py
>  class ArtifactAttribute:
this should model data stored in attribute API, so hash only

2021-08-19 14:02 UTC, pkasprzyk commented on neptune/new/internal/backends/hosted_neptune_backend.py
> +            return ArtifactAttribute(
that's different object...

2021-08-19 14:02 UTC, pkasprzyk commented on neptune/new/internal/backends/hosted_neptune_backend.py
> +            return ArtifactAttribute(
...than this one

2021-08-19 14:02 UTC, pkasprzyk commented on neptune/new/internal/backends/hosted_neptune_backend.py
> +            return ArtifactAttribute(
same here, this is Artifact API response

2021-08-19 14:24 UTC, pkasprzyk approved these changes

2021-08-19 14:44 UTC, merged