WIP: API implementation
neptune-ai/neptune-client pull request #706
Opened 2021-09-13 13:05 UTC by Raalsky

2021-09-15 15:35 UTC, pkasprzyk requested changes

2021-09-15 15:35 UTC, pkasprzyk commented on neptune/management/internal/api.py
> +    except HTTPBadRequest as e:
I'm pretty sure there are more potential bad request reasons that `ProjectAlreadyExists`... e.g. project key too long?

2021-09-16 07:34 UTC, Raalsky commented on neptune/management/internal/api.py
> +    except HTTPInternalServerError as e:
It's only for a while. A few updates for error messages and status has been created in Jira and planned for Sprint 26 :wink:

2021-09-16 08:43 UTC, pkasprzyk commented on neptune/management/internal/api.py
> +    except HTTPInternalServerError as e:
please leave some TODOs here, then :)

2021-09-16 11:19 UTC, pkasprzyk approved these changes

2021-09-16 14:32 UTC, merged