Pin jsonschema requirements for offline work
neptune-ai/neptune-client pull request #854
Opened 2022-02-25 07:37 UTC by HubertJaworski

2022-02-25 08:30 UTC, aniezurawski approved these changes

2022-02-25 11:42 UTC, Raalsky requested changes

2022-02-25 11:42 UTC, Raalsky commented on requirements.txt
> +# pinned to < 4.0.0 because bravado-core has invalid blacklist of schamas tha shouldn't be resolved
Add some info to CHANGELOG

2022-03-01 12:39 UTC, pkasprzyk commented
closing in accordance with internal discussions

2022-03-01 12:39 UTC, closed without merging