Docs for new 'column' parameter
neptune-ai/neptune-client pull request #988
Opened 2022-08-31 07:48 UTC by normandy7

2022-08-31 08:02 UTC, shnela requested changes

2022-08-31 08:02 UTC, shnela commented on neptune/new/metadata_containers/model.py
> +                    Fields: `["params/lr", "params/batch", "val/acc"]` - only these fields are included as columns.
The same is true for runs and models as well.

2022-08-31 10:44 UTC, normandy7 commented on neptune/new/metadata_containers/model.py
> +                    Fields: `["params/lr", "params/batch", "val/acc"]` - only these fields are included as columns.
Right, I suppose it doesn't hurt to mention it.

2022-09-05 12:08 UTC, shnela approved these changes

2022-09-05 12:09 UTC, merged